.coveragerc
It's not gonna work in PyCharm Coverage tool with parallel
=> Fix Test Coverage in IDE

tests/conftest.py, tests/controllers/__init__.py, tests/controllers/simple_controller.py, tests/entities/__init__.py, tests/entities/users.py, tests/test_controller.py, tests/urls.py
fix conftest
add SimpleController in test
add urls in test
add test for simple controller
=> Add test for controller

tests/routing/test_route_table.py, winter/controller.py, winter/routing/__init__.py, winter/routing/route_table.py
Now RouteTable does nothing. To be used in next PR!
=> Add RouteTable

samples/sample_winter_controller.py, tests/controllers/__init__.py, tests/controllers/controller_with_media_types_routing.py, tests/http/test_media_type.py, tests/schema/test_response_schema.py, tests/urls.py, winter/http/__init__.py, winter/http/media_type.py, winter/routing/routing.py
Swagger is in progress, maybe will make a separate PR
=> Add MediaType and Route.produces

tests/controllers/controller_with_path_parameters.py, tests/test_path_parameters_argument_resolver.py, winter/django.py, winter/http/__init__.py, winter/http/urls.py
=> Add registering url regexp

.travis.yml, tests/test_encodings.py, tox.ini, winter/schema/type_inspection.py, winter/type_utils.py
=> Support Python 3.7

winter/schema/inspectors.py
=> Set RouteAnnotation instead of Route

README.md
Add a simple sample of CRUD implementation with winter
=> Add a sample of CRUD implementation

tests/converters/test_converter.py
I do not how, but now coverage is 99(before merging it)
=> Added tests to optional converter

winter/django.py
=> Make Django views names more informative

winter/django.py
I believe convert_result_to_http_response shouldn't raise any exceptions we want to handle.
Am I right?
=> Extract else from try/except block in django dispatcher

tests/schema/test_type_inspection.py, winter_openapi/type_inspection.py
Add 'Set' type to register_type_inspector
=> Add set type to register_type_inspector

pyproject.toml
For some reason, only winter package is built in the package
=> Specify packages

.github/workflows/testing.yml, poetry.lock, pyproject.toml, winter_openapi/type_inspection.py
Reverts WinterFramework/winter#208
=> Revert "python 3.10 compatibility"

poetry.lock, pyproject.toml, tests/core/json/test_decoder.py, winter/core/json/decoder.py
https://github.com/WinterFramework/winter/issues/173
=> Add IntEnum decoder

CHANGELOG.md
Update change log after split sort method from paginate
=> Update change log after split sort method from paginate

poetry.lock, pyproject.toml, tests/winter_openapi/test_type_inspection.py, winter_openapi/type_inspection.py
Added StrEnum support for OpenAPI
=> Inspect StrEnum as an Enum, not string

CHANGELOG.md
Added changelog for my recent updates (9.6.4)
=> Changelog for 9.6.4 version

CHANGELOG.md, poetry.lock, pyproject.toml, tests/api/swagger_ui.py, tests/urls.py, tests/winter_openapi/test_swagger_ui.py, winter_openapi/__init__.py, winter_openapi/swagger_ui.py
It has the following benefits:
- No need to configure static files collection
- No need to setup whitenoise (or other static file server)
- No need to add drf_yasg to INSTALLED_APPS
=> Add Swagger UI and set version to 10.0.1

CHANGELOG.md, pyproject.toml, tests/messaging/events.py, tests/messaging/test_simple_event_bus.py, winter/core/component_method.py, winter/messaging/__init__.py, winter/messaging/event.py, winter/messaging/event_bus.py, winter/messaging/event_handler.py, winter/messaging/simple_event_bus.py
- EventBus interface added
- SimpleEventBus implementation
=> EventBus interface added, SimpleEventBus implementation

.github/workflows/testing.yml, README.md
Trigger github testing workflow for master branch and fix the build badge to show master branch status
=> Fix build badge

.github/workflows/testing.yml, .github/workflows/upload-package.yml
=> Update checkout and setup-python actions at the request of GitHub

pyproject.toml, tests/api/__init__.py, tests/api/api_with_requested_headers.py, tests/web/test_request_header.py, winter/__init__.py, winter/web/__init__.py, winter/web/request_header_annotation.py, winter/web/request_header_resolver.py
```
@winter.route_get('url/')
@winter.request_header('X-Auth-CompanyID', to='company_id')
def some_method(self, company_id: str):
print(company_id)
```
=> Add request_header feature

CHANGELOG.md, pyproject.toml, tests/api/api_with_throttling.py, tests/test_throttling.py, winter/web/throttling.py
This function allows resetting the accumulated throttling state based on condition in the business layer.
Refactor tests
=> Add reset function to throttling module

CHANGELOG.md
=> Fixed specification of optional properties in OpenAPI schema for models, which used as input parameters

CHANGELOG.md, pyproject.toml, winter_django/view.py
@winter.web.csrf_exempt didn't work for old views
=> Fix @winter.web.csrf_exempt for old views to keep compatability

CHANGELOG.md, README.md, pyproject.toml, tests/core/json/test_decoder.py, tests/core/json/test_undefined.py, tests/winter_openapi/test_swagger_auto_schema.py, winter/core/json/__init__.py, winter/core/json/decoder.py, winter/core/json/undefined.py, winter/core/utils/typing.py, winter_openapi/type_inspection.py
Check README.md for example usage
=> Add winter.core.json.Undefined class to represent absence of value in JSON object
